// <auto-generated />
using EFGetStarted.AspNetCore.NewDb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFGetStarted.AspNetCore.NewDb.Migrations
{
    [DbContext(typeof(ArqsiContext))]
    [Migration("20181008153718_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Acabamento", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("Id");

                    b.ToTable("Acabamento");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Material", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcabamentoId");

                    b.Property<string>("Nome");

                    b.HasKey("id");

                    b.HasIndex("AcabamentoId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EFGetStarted.AspNetCore.NewDb.Models.Material", b =>
                {
                    b.HasOne("EFGetStarted.AspNetCore.NewDb.Models.Acabamento", "Acabamento")
                        .WithMany()
                        .HasForeignKey("AcabamentoId");
                });
#pragma warning restore 612, 618
        }
    }
}
