// <auto-generated />
using System;
using ArqsiArmario.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArqsiArmario.Migrations
{
    [DbContext(typeof(ArqsiContext))]
    [Migration("20181013163539_DataBaseMig")]
    partial class DataBaseMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArqsiArmario.Models.Acabamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MaterialId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Acabamentos");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaId");

                    b.Property<bool>("Composto");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Dimensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlturaId");

                    b.Property<int?>("LarguraId");

                    b.Property<int?>("ProfundidadeId");

                    b.HasKey("Id");

                    b.HasIndex("AlturaId");

                    b.HasIndex("LarguraId");

                    b.HasIndex("ProfundidadeId");

                    b.ToTable("Dimensoes");
                });

            modelBuilder.Entity("ArqsiArmario.Models.DimensaoDC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AlturaMax");

                    b.Property<float>("AlturaMin");

                    b.HasKey("Id");

                    b.ToTable("DimensaoDC");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcabamentoId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaId");

                    b.Property<bool>("Composto");

                    b.Property<int?>("DimensaoId");

                    b.Property<int?>("MaterialId");

                    b.Property<string>("Nome");

                    b.Property<int?>("ProdutoId");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DimensaoId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Valor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DimensaoDCId");

                    b.Property<int>("ValorDiscreto");

                    b.HasKey("Id");

                    b.HasIndex("DimensaoDCId");

                    b.ToTable("Valor");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Acabamento", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Material")
                        .WithMany("Acabamentos")
                        .HasForeignKey("MaterialId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Categoria", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Categoria", "CategoriaPai")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Dimensao", b =>
                {
                    b.HasOne("ArqsiArmario.Models.DimensaoDC", "Altura")
                        .WithMany()
                        .HasForeignKey("AlturaId");

                    b.HasOne("ArqsiArmario.Models.DimensaoDC", "Largura")
                        .WithMany()
                        .HasForeignKey("LarguraId");

                    b.HasOne("ArqsiArmario.Models.DimensaoDC", "Profundidade")
                        .WithMany()
                        .HasForeignKey("ProfundidadeId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Produto", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId");

                    b.HasOne("ArqsiArmario.Models.Dimensao", "Dimensao")
                        .WithMany()
                        .HasForeignKey("DimensaoId");

                    b.HasOne("ArqsiArmario.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("ArqsiArmario.Models.Produto")
                        .WithMany("Produtos")
                        .HasForeignKey("ProdutoId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Valor", b =>
                {
                    b.HasOne("ArqsiArmario.Models.DimensaoDC")
                        .WithMany("ListaDiscreta")
                        .HasForeignKey("DimensaoDCId");
                });
#pragma warning restore 612, 618
        }
    }
}
