// <auto-generated />
using System;
using ArqsiArmario.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArqsiArmario.Migrations
{
    [DbContext(typeof(ArqsiContext))]
    [Migration("20181012151432_DataBaseMig")]
    partial class DataBaseMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArqsiArmario.Models.Acabamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Acabamentos");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoriaId");

                    b.Property<bool>("Composto");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Dimensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Dimensoes");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AcabamentoId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("AcabamentoId");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Composto");

                    b.Property<int?>("MaterialId");

                    b.Property<string>("Nome");

                    b.Property<int?>("ProdutoId");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Categoria", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Categoria", "CategoriaPai")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Material", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Acabamento", "Acabamento")
                        .WithMany()
                        .HasForeignKey("AcabamentoId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Produto", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("ArqsiArmario.Models.Produto")
                        .WithMany("Produtos")
                        .HasForeignKey("ProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
