// <auto-generated />
using System;
using ArqsiArmario.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArqsiArmario.Migrations
{
    [DbContext(typeof(ArqsiContext))]
    partial class ArqsiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArqsiArmario.Models.Acabamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MaterialId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Acabamentos");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Dimensao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DimContinuaId");

                    b.HasKey("Id");

                    b.HasIndex("DimContinuaId");

                    b.ToTable("Dimensoes");
                });

            modelBuilder.Entity("ArqsiArmario.Models.DimensaoContinua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float?>("AlturaMaxima");

                    b.Property<float>("AlturaMinima");

                    b.Property<float?>("LarguraMaxima");

                    b.Property<float>("LarguraMinima");

                    b.Property<float>("ProfundidadeMinima");

                    b.Property<float?>("ProfunidadeMaxima");

                    b.HasKey("Id");

                    b.ToTable("DimensaoContinua");
                });

            modelBuilder.Entity("ArqsiArmario.Models.DimensaoDiscreta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Altura");

                    b.Property<int?>("DimensaoId");

                    b.Property<float>("Largura");

                    b.Property<float>("Profundidade");

                    b.HasKey("Id");

                    b.HasIndex("DimensaoId");

                    b.ToTable("DimensaoDiscreta");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcabamentoId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaId");

                    b.Property<int>("MaterialId");

                    b.Property<string>("Nome");

                    b.Property<int?>("ProdutoId");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Acabamento", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Material")
                        .WithMany("Acabamentos")
                        .HasForeignKey("MaterialId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Dimensao", b =>
                {
                    b.HasOne("ArqsiArmario.Models.DimensaoContinua", "DimContinua")
                        .WithMany()
                        .HasForeignKey("DimContinuaId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.DimensaoDiscreta", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Dimensao")
                        .WithMany("DimDiscreta")
                        .HasForeignKey("DimensaoId");
                });

            modelBuilder.Entity("ArqsiArmario.Models.Produto", b =>
                {
                    b.HasOne("ArqsiArmario.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ArqsiArmario.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ArqsiArmario.Models.Produto")
                        .WithMany("Produtos")
                        .HasForeignKey("ProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
